component: scf
name: ap-guangzhou_default_APIGWBasicDemo
inputs:
  name: APIGWBasicDemo
  src:
    src: ./src
  handler: index.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3
  triggers:
    - type: apigw
      name: SCF_API_SERVICE
      protocols:
        - http
      environment: release
      apis:
        - path: /
          method: ANY
          function:
            isIntegratedResponse: true

