component: scf
name: ap-guangzhou_default_LogAnalysis
inputs:
  name: LogAnalysis
  src:
    src: ./src
  handler: index.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  environment:
    - key: dbhost
      value: db host
    - key: dbport
      value: db port
    - key: dbuser
      value: db user name
    - key: dbpwd
      value: db password
    - key: dbname
      value: db name
    - key: cosregion
      value: cos region
  timeout: 10
  triggers:
    - type: cos
      enable: true
      bucket: 
      events: 'cos:ObjectCreated:*'
