component: scf
name: cdn_refresh
org: app
app: cosdemo
stage: dev

inputs:
  name: cos_cdn_PurgeUrlsCache
  src: ./src
  runtime: Python2.7
  region: ap-shanghai  #需要替换的字段
  handler: index.main_handler
  timeout: 20
  role: SCF_QcsRole  #需要确认是否有授权CDN的接口操作权限
  environment:
    variables:
      #需要替换的字段
      url_cdn: #'https://serverless-demo-1256608914.file.myqcloud.com'
      region: #ap-shanghai
  events: # 触发器
    - cos: # cos触发器
        name: ${output:${stage}:${app}:cosdemo.cosOrigin}
        parameters:
          bucket: ${output:${stage}:${app}:cosdemo.cosOrigin}
          events: 'cos:ObjectCreated:*'
          enable: true



