component: scf
name: ap-guangzhou_default_TimerReport
inputs:
  name: TimerReport
  src:
    src: ./src
  handler: index.main_handler
  runtime: Php7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3
  triggers:
    - type: timer
      name: timer
      cronExpression: 0 0 */1 * * * *
      argument: ''
      enable: true
