component: scf
name: ap-guangzhou_default_CDNDispatchLogJobs
inputs:
  name: CDNDispatchLogJobs
  src:
    src: ./src
  handler: index.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 300
  triggers:
    - type: cos
      enable: true
      bucket: 
      events: 'cos:ObjectCreated:*'
