component: scf
name: ap-guangzhou_default_WebsocketRegisterFunction
inputs:
  name: WebsocketRegisterFunction
  src:
    src: ./src
  handler: index.main_handler
  runtime: Nodejs8.9
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3

