component: scf
name: ap-guangzhou_default_Cos_Merge_File
org: app
app: cosdemo
stage: dev
inputs:
  name: Cos_Merge_File
  src: ./
  description: 本示例使用 COS 触发器，完成CDN缓存刷新动作
  handler: index.main_handler
  runtime: Nodejs8.9
  namespace: default
  region: ap-guangzhou
  memorySize: 256
  timeout: 900
  events: # 触发器
    - cos: # cos触发器
        name: ${output:${stage}:${app}:cosdemo.cosOrigin}
        parameters:
          bucket: ${output:${stage}:${app}:cosdemo.cosOrigin}
          events: 'cos:ObjectCreated:*'
          enable: true
