component: scf
name: ap-guangzhou_default_unpack_to_cos
org: app
app: cosdemo
stage: dev
inputs:
  name: unpack_to_cos
  src: ./
  description: >-
    本示例通过配置COS触发，上传到COS的压缩包，使用SCF下载并本地解压，支持中文字段解压，并把解压后的文件上传到COS另一个targetBucket环境变量指定的存储桶中，支持如下压缩格式：ZIP,
    RAR, 7Z, BZIP2, GZIP, TAR, XZ
  handler: unpack_to_cos.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 900
  events: # 触发器
    - cos: # cos触发器
        name: ${output:${stage}:${app}:cosdemo.cosOrigin}
        parameters:
          bucket: ${output:${stage}:${app}:cosdemo.cosOrigin}
          events: 'cos:ObjectCreated:*'
          enable: true
