component: scf
name: COS_SyncData_AcrossRegion
org: scf
app: scfApp
stage: test

inputs:
  name: COS_SyncData_AcrossRegion
  src: 
    src: ./src
  runtime: Python3.6
  region: ap-beijing  #需要替换的字段
  handler: index.main_handler
  memorySize: 128
  timeout: 100
  role: SCF_QcsRole  #需要确认是否有授权cos的copy接口操作权限
  environment:
    variables:  #环境变量
      target_bucket: 'function-scf-1256608914'  #需要替换的字段 
      target_region: ap-shanghai #需要替换的字段
      source_region: ap-beijing  #需要替换的字段
      
  events: # 触发器
    - cos: # cos触发器
        name: ${output:${stage}:${app}:cosdemo.cosOrigin}
        parameters:
          bucket: ${output:${stage}:${app}:cosdemo.cosOrigin}
          events: 'cos:ObjectCreated:*'
          enable: true
          filter:
            prefix: copy/   #需要替换的字段，可选，配置前缀过滤


