component: scf
name: ap-guangzhou_default_KafkaMsgToCOS
inputs:
  name: KafkaMsgToCOS
  src:
    src: ./src
  description: 本示例通过配置kafka触发器，从kafka接收到消息后，写入文件并上传到cos中
  handler: index.main_handler
  runtime: Nodejs8.9
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3
  triggers:
    - type: ckafka
      enable: true
      name: 
      topic: 
      maxMsgNum: 100
      offset: latest
      retry: 10000
