component: scf
name: ap-guangzhou_default_AddTextToPictures
inputs:
  name: AddTextToPictures
  src:
    src: ./src
  runtime: Python2.7
  region: ap-guangzhou
  handler: index.main_handler
  memorySize: 512
  timeout: 60
  environment:
    - key: region
      value: the region of target bucket
    - key: target_bucket
      value: target bucket name
    - key: target_path
      value: path of target bucket
  triggers:
    - type: apigw
      name: SCF_API_SERVICE
      protocols:
        - http
        - https
      environment: release
      netTypes:
        - OUTER
      apis:
        - path: /AddTextToPictures
          method: ANY
          function:
            isIntegratedResponse: true
