component: scf
name: ap-guangzhou_default_CkafkaSCFElasticsearch
inputs:
  name: CkafkaSCFElasticsearch
  src: ./src
  handler: index.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  environment:
    - key: ES_Address
      value: ES address/ES 地址
    - key: ES_User
      value: ES user name/ ES 用户名
    - key: ES_Password
      value: ES password/ES 密码
  timeout: 30
  triggers:
    - type: ckafka
      name: 
      enable: true
      topic: 
      maxMsgNum: 50
      offset: latest
      retry: 10000
