component: scf
name: ap-guangzhou_default_WriteToES
inputs:
  name: WriteToES
  src:
    src: ./src
  handler: index.main_handler
  runtime: Nodejs8.9
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3
  triggers:
    - type: timer
      enable: true
      name: timer
      cronExpression: 0 0 */1 * * * *
      argument: ''
