component: scf
name: ap-guangzhou_default_MPS_SCF_COS
inputs:
  name: MPS_SCF_COS
  src:
    src: ./src
  handler: index.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 5
  triggers:
    - type: mps
