component: scf
name: ap-guangzhou_default_CkafkaLoadToCDWByTrigger
inputs:
  name: CkafkaLoadToCDWByTrigger
  src:
    src: ./src
  handler: index.main_handler
  runtime: Python3.6
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  environment:
    - key: DB_DATABASE
      value: DB database
    - key: DB_HOST
      value: DB host
    - key: DB_USER
      value: DB user name
    - key: DB_PASSWORD
      value: DB password
    - key: DB_SCHEMA
      value: DB schema
    - key: DB_TABLE
      value: DB table
  timeout: 60
  triggers:
    - type: ckafka
      name: 
      enable: true
      topic: 
      maxMsgNum: 100
      offset: latest
      retry: 10000
