component: scf
name: ap-guangzhou_default_COSCDNRefresh
inputs:
  src:
    src: ./src
  handler: index.main_handler
  memorySize: 256
  name: COSCDNRefresh
  region: ap-guangzhou
  runtime: Nodejs8.9
  timeout: 900
  triggers:
    - type: cos
      enable: true
      events: 'cos:ObjectCreated:*'

