component: scf
name: ap-guangzhou_default_Thumbnail
org: app
app: cosdemo
stage: dev
inputs:
  name: Thumbnail
  src: ./
  description: >-
    This demo need to config COS trigger. When object has been upload to COS
    bucket, the SCF will download it to /tmp and compress it. 本示例配置了 COS
    触发器，当有文件上传到对应的 COS bucket时，会触发云函数执行，并把文件下载到本地临时目录，用做后续处理
  handler: Thumbnail.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 5
  events: # 触发器
    - cos: # cos触发器
        name: ${output:${stage}:${app}:cosdemo.cosOrigin}
        parameters:
          bucket: ${output:${stage}:${app}:cosdemo.cosOrigin}
          events: 'cos:ObjectCreated:*'
          enable: true


