component: scf
name: ap-guangzhou_default_VideoToRTMP
inputs:
  name: VideoToRTMP
  src: 
    src: ./src
  runtime: Python3.6
  region: ap-guangzhou
  handler: index.main_handler
  memorySize: 3072
  timeout: 86400
  asyncRunEnable: true
  traceEnable: true
  triggers:
    - type: apigw
      name: SCF_API_SERVICE
      protocols:
        - http
        - https
      environment: release
      description: the serverless service
      apis:
        - path: /videoToRTMP
          method: ANY
          function: 
            isIntegratedResponse: false
