component: scf
name: ap-guangzhou_default_CkafkaTriggerTemplate
inputs:
  name: CkafkaTriggerTemplate
  src:
    src: ./src
  handler: index.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 5
  triggers:
    - type: ckafka
      name: 
      topic: 
      maxMsgNum: 50
      offset: latest
      enable: true
