component: scf
name: ap-guangzhou_default_CLSLogETL
inputs:
  name: CLSLogETL
  src:
    src: ./src
  handler: index.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 300
