component: scf
name: ap-guangzhou_default_CDNEdgepack
inputs:
  name: CDNEdgepack
  src:
    src: ./src
  runtime: Python2.7
  region: ap-guangzhou
  handler: index.main_handler
  memorySize: 128
  timeout: 900
  triggers:
    - type: cos
      bucket: 
      events: 'cos:ObjectCreated:*'
      enable: true
