# serverless.yml 
app: springbootAppName
stage: dev 
component: springboot 
name: springbootInstance

inputs:
  region: ap-guangzhou 
  functionName: ${name}
  runtime: Java8
  src: ./
  projectJarName: 'my-springboot.jar'

  layers:
    - name: layerName
      version: 1

  functionConf: # 函数配置相关
    handler: 'example.MyHandler::mainHandler'
    timeout: 30 # 超时时间，单位秒
    memorySize: 256 # 内存大小，单位MB

  apigatewayConf: #  api网关配置
    customDomains: # 自定义域名绑定
      - domain: abc.com # 待绑定的自定义的域名
        certificateId: abcdefg # 待绑定自定义域名的证书唯一 ID
        # 如要设置自定义路径映射，请设置为 false
        isDefaultMapping: false
        # 自定义路径映射的路径。使用自定义映射时，可一次仅映射一个 path 到一个环境，也可映射多个 path 到多个环境。并且一旦使用自定义映射，原本的默认映射规则不再生效，只有自定义映射路径生效。
        pathMappingSet:
          - path: /
            environment: release
        protocols: # 绑定自定义域名的协议类型，默认与服务的前端协议一致。
          - http # 支持http协议
          - https # 支持https协议
    protocols:
      - http
      - https
    environment: release
    serviceTimeout: 60