component: scf
name: ap-guangzhou_default_APIGWHexoDemo
inputs:
  name: APIGWHexoDemo
  src:
    src: ./src
  handler: index.main_handler
  runtime: Nodejs8.9
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3
  triggers:
    - type: apigw
      name: SCF_API_SERVICE
      protocols:
        - http
      environment: release
      apis:
        - path: /WebSite
          method: ANY
          function:
            isIntegratedResponse: true

