component: scf
name: transcode
org: app
app: cosdemo
stage: dev

inputs:
  name: transcode
  src: 
    src: ./
  runtime: Python3.6
  region: ap-shanghai #需要替换的字段
  handler: index.main_handler
  memorySize: 3072
  timeout: 300
  role: SCF_QcsRole   #需要授权：cos bucket文件读写，cdn预热/刷新权限
  vpcConfig: # 私有网络配置
    subnetId: 'subnet-03jndatv'  #需要替换的字段
    vpcId: 'vpc-9mp2jk1a'  #需要替换的字段
  environment:
    variables:
      #region: ap-shanghai  #需要替换的字段
      #target_bucket: serverless-demo-1256608914  #需要替换的字段
      #target_path: /transcode  #需要替换的字段
  events: # 触发器
    - cos: # cos触发器
        name: ${output:${stage}:${app}:cosdemo.cosOrigin}
        parameters:
          bucket: ${output:${stage}:${app}:cosdemo.cosOrigin}
          events: 'cos:ObjectCreated:*'
          enable: true


