component: scf
name: ap-guangzhou_default_VscodeAct
inputs:
  name: VscodeAct
  src:
    src: ./src
  handler: index.main_handler
  runtime: Nodejs8.9
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 5
  triggers:
    - type: apigw
      name: SCF_API_SERVICE
      protocols:
        - http
      environment: release
      netTypes:
        - OUTER
      apis:
        - path: /
          method: GET
          function:
            isIntegratedResponse: true
