component: scf
name: ap-guangzhou_default_ZipFile
inputs:
  name: ZipFile
  src:
    src: ./src
  handler: index.main_handler
  runtime: Nodejs12.16
  namespace: default
  region: ap-guangzhou
  memorySize: 1024
  timeout: 86400