component: scf
name: ap-guangzhou_default_trtc
inputs:
  src:
    src: ./src
  region: ap-shanghai
  name: TRTC
  runtime: Java8
  handler: example.Handler::handleRequest
  memorySize: 1024
  timeout: 43200
  asyncRunEnable: true
  traceEnable: true
  triggers:
    - type: apigw
      name: SCF_API_SERVICE
      protocols:
        - http
        - https
      environment: release
      description: the serverless service
      apis:
        - path: /trtc
          method: ANY
          function: 
            isIntegratedResponse: false

 