component: scf
name: ap-guangzhou_default_ESCuratorClear
inputs:
  name: ESCuratorClear
  src:
    src: ./src
  handler: index.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 10
  triggers:
    - type: timer
      name: 
      cronExpression: 0 0 */1 * * * *
      argument: ''
      enable: true
