name: python2-unpackanduploadtocos # 项目模板的名字 
displayName:  压缩包解压 # 项目模板展示在控制台的名称（中文）
author: Tencent Cloud, Inc. # 作者的名字
org: Tencent Cloud, Inc. # 组织名称，可选
description:  This demo need to config COS trigger. When archive file has been upload to COS bucket, the SCF will download it to /tmp and unpack it.  # 英文描述
description-i18n:
  zh-cn: 本示例通过配置COS触发，上传到COS的压缩包，使用SCF下载并本地解压，支持中文字段解压，并把解压后的文件上传到COS另一个targetBucket环境变量指定的存储桶中，支持如下压缩格式：ZIP, RAR, 7Z, BZIP2, GZIP, TAR, XZ # 中文描述
type: template #类型：模版
keywords: tencent, scf, COS, Python2.7, unzip, archive, COSUnpackDemo # 关键字
repo: https://github.com/tencentyun/serverless-demo/tree/master/Python2.7-UnpackAndUploadToCOS # 源代码
readme: https://github.com/tencentyun/serverless-demo/tree/master/Python2.7-UnpackAndUploadToCOS/README.md # 详细的说明文件
license: MIT # 版权声明
src: # 描述项目中的哪些文件需要作为模板发布
  src: ./src # 指定具体的相对目录，此目录下的文件将作为模板发布
  exclude: #描述在指定的目录内哪些文件应该被排除
    # 通常你希望排除
    # 1. 包含secrets的文件
    # 2. .git git源代码管理的相关文件
    # 3. node_modules等第三方依赖文件