component: scf
name: ap-guangzhou_default_COSCDNPushUrlsCache
inputs:
  name: COSCDNPushUrlsCache 
  src:
    src: ./src
  runtime: Python3.6
  region: ap-guangzhou
  handler: index.main_handler
  memorySize: 128
  timeout: 20
  triggers:
    - type: cos
      enable: true
      events: 'cos:ObjectCreated:*'
